language: c
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq fglrx=2:8.960-0ubuntu1 opencl-headers lcov
  - gem install coveralls-lcov
  - sh ./utilities/get_cgreen.sh
  - export CGREEN_CHILD_EXIT_WITH_FLUSH=TRUE
script:
  - mkdir -p build
  - cd build
  - cmake -DCGREEN_ROOT_DIR=`pwd`/../cgreen -DECL_BUILD_TESTS=ON -DECL_RUN_EXAMPLES_AS_TEST=ON -DECL_ENABLE_COVERAGE=ON -DBUILD_SHARED_LIBS=ON  ..
  - make -j2
  - ctest -j2 --output-on-failure
after_success:
  - lcov -d tests -d src -base-directory .. -c -o coverage.info
  - lcov --remove coverage.info '/usr/*' -o coverage.info
  - lcov --remove coverage.info 'cgreen/*' -o coverage.info
  - lcov --remove coverage.info 'tests/*' -o coverage.info
  - cd ..
  - coveralls-lcov build/coverage.info
